import React, { useState, useEffect, useCallback, useMemo } from 'react';
import DashboardLayout from '@/components/layout/DashboardLayout';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { Checkbox } from '@/components/ui/checkbox';
import { toast } from 'sonner';
import { Plus, Pencil, Trash2, Loader2, ClipboardList, Users, BookOpen, Search, Wand2 } from 'lucide-react';
import api from '@/lib/api';
import { getProgramColorClasses } from '@/utils/programColors';

export default function CoursesPage() {
  const [courses, setCourses] = useState([]);
  const [programs, setPrograms] = useState([]);
  const [subjects, setSubjects] = useState([]);
  const [teachers, setTeachers] = useState([]);
  const [students, setStudents] = useState([]);
  const [loading, setLoading] = useState(true);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editing, setEditing] = useState(null);
  const [form, setForm] = useState({ 
    name: '', 
    program_id: '', 
    subject_id: '',  // Keep for backward compatibility
    subject_ids: [],  // Multiple subjects
    year: new Date().getFullYear(), 
    month: 'Enero',
    student_ids: [],
    start_date: '',
    end_date: '',
    module_dates: {}  // e.g., {"1": {"start": "2026-01-01", "end": "2026-06-30"}}
  });
  const [saving, setSaving] = useState(false);
  const [subjectSearch, setSubjectSearch] = useState('');
  const [studentSearch, setStudentSearch] = useState('');
  const [isAutoGeneratedName, setIsAutoGeneratedName] = useState(false);
  const [moduleDateErrors, setModuleDateErrors] = useState({});
  // List-view filters
  const [listSearch, setListSearch] = useState('');
  const [listFilterProgram, setListFilterProgram] = useState('all');
  const [listFilterSubject, setListFilterSubject] = useState('all');

  const fetchData = useCallback(async () => {
    try {
      const [cRes, pRes, sRes, tRes, stRes] = await Promise.all([
        api.get('/courses'), api.get('/programs'), api.get('/subjects'),
        api.get('/users?role=profesor'), api.get('/users?role=estudiante')
      ]);
      setCourses(cRes.data); setPrograms(pRes.data); setSubjects(sRes.data);
      setTeachers(tRes.data); setStudents(stRes.data);
    } catch (err) {
      toast.error('Error cargando datos');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetchData(); }, [fetchData]);

  const getName = (arr, id) => arr.find(i => i.id === id)?.name || '-';
  const filteredSubjects = form.program_id ? subjects.filter(s => String(s.program_id) === String(form.program_id)) : subjects;

  // Returns a student's status for the given program (falls back to global estado)
  const getStudentStatusForProgram = (student, programId) => {
    if (programId && student.program_statuses) {
      return student.program_statuses[programId] || student.estado || 'activo';
    }
    return student.estado || 'activo';
  };

  // Derive the module number that this group targets from selected subjects (most common module among selections)
  const groupModule = useMemo(() => {
    if (form.subject_ids.length === 0) return null;
    const moduleCounts = {};
    for (const sid of form.subject_ids) {
      const s = subjects.find(x => x.id === sid);
      const mod = s?.module_number != null ? parseInt(s.module_number, 10) : null;
      if (mod != null && Number.isFinite(mod)) moduleCounts[mod] = (moduleCounts[mod] || 0) + 1;
    }
    const entries = Object.entries(moduleCounts);
    if (entries.length === 0) return null;
    return parseInt(entries.sort((a, b) => b[1] - a[1])[0][0], 10);
  }, [form.subject_ids, subjects]);
  
  // Filtered courses for the list view
  const filteredCourses = courses.filter(c => {
    const nameMatch = listSearch === '' || (c.name || '').toLowerCase().includes(listSearch.toLowerCase());
    const programMatch = listFilterProgram === 'all' || String(c.program_id) === String(listFilterProgram);
    const subjectMatch = listFilterSubject === 'all' || (c.subject_ids || []).includes(listFilterSubject) || c.subject_id === listFilterSubject;
    return nameMatch && programMatch && subjectMatch;
  });
  
  // Returns the date one day after the given YYYY-MM-DD string, or '' if not provided
  const dayAfter = (dateStr) => {
    if (!dateStr) return '';
    const d = new Date(dateStr + 'T00:00:00Z');
    d.setUTCDate(d.getUTCDate() + 1);
    return d.toISOString().slice(0, 10);
  };

  // Validate module_dates order and return error map {`${moduleNum}_${field}`: msg}
  const validateModuleDates = (module_dates, count) => {
    const errors = {};
    for (let i = 1; i <= count; i++) {
      const dates = module_dates[i] || {};
      const { start, end, recovery_close } = dates;
      if (start && end && end < start) {
        errors[`${i}_end`] = 'La fecha de cierre debe ser >= fecha de inicio';
      }
      if (end && recovery_close && recovery_close < end) {
        errors[`${i}_recovery_close`] = 'El cierre de recuperaciones debe ser >= fecha de cierre';
      }
      if (i > 1) {
        const prev = module_dates[i - 1] || {};
        const prevBoundary = prev.recovery_close || prev.end;
        if (prevBoundary && start && start <= prevBoundary) {
          errors[`${i}_start`] = `La fecha de inicio del Módulo ${i} debe ser posterior al cierre del Módulo ${i - 1} (${prevBoundary})`;
        }
      }
    }
    return errors;
  };
  
  // Get the selected program to determine module count
  const selectedProgram = programs.find(p => p.id === form.program_id);
  const programModuleCount = selectedProgram?.modules?.length || 0;
  // When editing an existing course, preserve its original module count from stored module_dates
  // so that changes to the program's module count don't affect already-created groups
  const existingModuleCount = editing ? Object.keys(editing.module_dates || {}).length : 0;
  const moduleCount = editing ? (existingModuleCount || programModuleCount) : programModuleCount;
  
  const formatGrupoSuggestion = (month, year, programId) => {
    if (!month || !year || !programId) return '';
    const programName = getName(programs, programId);
    if (!programName || programName === '-') return '';
    const lastTwoWords = programName.split(' ').slice(-2).join(' ').toUpperCase();
    return `${month.toUpperCase()}-${year} - ${lastTwoWords}`;
  };

  const openCreate = () => {
    setEditing(null);
    setForm({ 
      name: '', 
      program_id: '', 
      subject_id: '',  // Keep for backward compatibility
      subject_ids: [],  // Multiple subjects
      year: new Date().getFullYear(), 
      month: 'Enero',
      student_ids: [],
      start_date: '',
      end_date: '',
      module_dates: {}
    });
    setSubjectSearch('');
    setStudentSearch('');
    setIsAutoGeneratedName(false);
    setModuleDateErrors({});
    setDialogOpen(true);
  };

  const openEdit = (course) => {
    setEditing(course);
    // Extract month and year from course name if possible
    const monthMatch = course.name.match(/(Enero|Febrero|Marzo|Abril|Mayo|Junio|Julio|Agosto|Septiembre|Octubre|Noviembre|Diciembre)/i);
    const yearMatch = course.name.match(/\d{4}/);
    setForm({ 
      name: course.name, 
      program_id: course.program_id, 
      subject_id: course.subject_id || '',  // Backward compatibility
      subject_ids: course.subject_ids || (course.subject_id ? [course.subject_id] : []),  // Convert single to array
      year: yearMatch ? parseInt(yearMatch[0]) : new Date().getFullYear(),
      month: monthMatch ? monthMatch[0] : 'Enero',
      student_ids: course.student_ids || [],
      start_date: course.start_date || '',
      end_date: course.end_date || '',
      module_dates: course.module_dates || {}
    });
    setSubjectSearch('');
    setStudentSearch('');
    setIsAutoGeneratedName(false);
    setModuleDateErrors({});
    setDialogOpen(true);
  };

  const toggleStudent = (studentId) => {
    setForm(prev => ({
      ...prev,
      student_ids: prev.student_ids.includes(studentId)
        ? prev.student_ids.filter(id => id !== studentId)
        : [...prev.student_ids, studentId]
    }));
  };

  const handleSave = async () => {
    if (!form.name.trim()) { toast.error('Nombre del grupo requerido'); return; }
    if (form.subject_ids.length === 0) { toast.error('Debes seleccionar al menos una materia'); return; }
    
    // Validate module date order before submitting
    const dateErrors = validateModuleDates(form.module_dates, moduleCount);
    setModuleDateErrors(dateErrors);
    if (Object.keys(dateErrors).length > 0) {
      toast.error('Corrige las fechas de módulo antes de guardar');
      return;
    }
    
    setSaving(true);
    try {
      const saveData = {
        name: form.name,
        subject_ids: form.subject_ids,
        student_ids: form.student_ids,
        start_date: form.start_date || null,
        end_date: form.end_date || null,
        module_dates: form.module_dates || {}
      };
      
      if (editing) {
        await api.put(`/courses/${editing.id}`, saveData);
        toast.success('Curso actualizado');
      } else {
        await api.post('/courses', {
          ...saveData,
          program_id: form.program_id,
          subject_id: form.subject_ids[0] || null,  // For backward compatibility, use first subject
          year: form.year
        });
        toast.success('Curso creado');
      }
      setDialogOpen(false);
      fetchData();
    } catch (err) {
      toast.error('Error guardando curso: ' + (err.response?.data?.detail || err.message));
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async (id) => {
    if (!window.confirm('¿Eliminar este grupo?')) return;
    try {
      await api.delete(`/courses/${id}`);
      toast.success('Grupo eliminado');
      fetchData();
    } catch (err) {
      if (err.response?.status === 400 && err.response?.data?.detail?.includes('force=true')) {
        const detail = err.response.data.detail;
        if (window.confirm(
          `⚠️ ADVERTENCIA: ${detail}\n\n` +
          'Los estudiantes NO serán borrados, solo desmatriculados del grupo.\n\n' +
          '¿Deseas continuar y eliminar el grupo de todas formas?'
        )) {
          try {
            await api.delete(`/courses/${id}`, { params: { force: true } });
            toast.success('Grupo eliminado (estudiantes desmatriculados)');
            fetchData();
          } catch (err2) {
            toast.error(err2.response?.data?.detail || 'Error eliminando grupo');
          }
        }
      } else {
        toast.error(err.response?.data?.detail || 'Error eliminando grupo');
      }
    }
  };

  return (
    <DashboardLayout>
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-4xl font-bold font-heading">Grupos</h1>
            <p className="text-muted-foreground mt-1 text-xl">Gestiona grupos por programa, materia y cohorte</p>
          </div>
          <Button onClick={openCreate} size="lg"><Plus className="h-5 w-5" /> Nuevo Grupo</Button>
        </div>

        {/* List filters */}
        <div className="flex flex-col sm:flex-row gap-3">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Buscar por nombre de grupo..."
              value={listSearch}
              onChange={(e) => setListSearch(e.target.value)}
              className="pl-9"
            />
          </div>
          <Select value={listFilterProgram} onValueChange={setListFilterProgram}>
            <SelectTrigger className="w-full sm:w-56">
              <SelectValue placeholder="Filtrar por técnico" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">Todos los técnicos</SelectItem>
              {programs.map(p => <SelectItem key={p.id} value={String(p.id)}>{p.name}</SelectItem>)}
            </SelectContent>
          </Select>
          <Select value={listFilterSubject} onValueChange={setListFilterSubject}>
            <SelectTrigger className="w-full sm:w-56">
              <SelectValue placeholder="Filtrar por materia" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">Todas las materias</SelectItem>
              {(listFilterProgram !== 'all' ? subjects.filter(s => String(s.program_id) === listFilterProgram) : subjects)
                .map(s => <SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}
            </SelectContent>
          </Select>
        </div>

        {loading ? (
          <div className="flex justify-center py-20"><Loader2 className="h-8 w-8 animate-spin text-primary" /></div>
        ) : filteredCourses.length === 0 ? (
          <Card className="shadow-card"><CardContent className="p-10 text-center">
            <ClipboardList className="h-12 w-12 text-muted-foreground mx-auto mb-3" />
            <p className="text-muted-foreground">{courses.length === 0 ? 'No hay grupos creados' : 'No hay grupos que coincidan con los filtros'}</p>
          </CardContent></Card>
        ) : (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
            {filteredCourses.map((c) => (
              <Card key={c.id} className={`shadow-card hover:shadow-card-hover transition-shadow border-2 ${getProgramColorClasses(programs, c.program_id)}`}>
                <CardHeader className="pb-3">
                  <div className="flex items-start justify-between">
                    <CardTitle className="text-base font-heading">{c.name}</CardTitle>
                    <div className="flex gap-1">
                      <Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => openEdit(c)}><Pencil className="h-3 w-3" /></Button>
                      <Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => handleDelete(c.id)}><Trash2 className="h-3 w-3 text-destructive" /></Button>
                    </div>
                  </div>
                </CardHeader>
                <CardContent>
                  <div className="space-y-2">
                    <div className="flex items-center gap-2">
                      <BookOpen className="h-4 w-4 text-primary shrink-0" />
                      <span className="text-lg font-bold text-foreground truncate">{getName(programs, c.program_id)}</span>
                    </div>
                    {c.subject_ids && c.subject_ids.length > 0 && (
                      <div className="flex flex-wrap gap-1">
                        {c.subject_ids.map(subjectId => (
                          <Badge key={subjectId} variant="secondary" className="text-xs">
                            {getName(subjects, subjectId)}
                          </Badge>
                        ))}
                      </div>
                    )}
                    <div className="flex gap-2 flex-wrap pt-1">
                      <Badge variant="secondary">{c.year}</Badge>
                      <Badge variant="outline">{c.student_ids?.length || 0} estudiantes</Badge>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </div>

      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="text-xl">{editing ? 'Editar Grupo' : 'Nuevo Grupo'}</DialogTitle>
            <DialogDescription className="text-base">Configura el grupo y asigna estudiantes y materias</DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            {!editing && (
              <>
                <div className="space-y-2">
                  <Label className="text-base">Programa</Label>
                  <Select value={form.program_id} onValueChange={(v) => {
                    if (form.subject_ids.length > 0) {
                      if (window.confirm('¿Cambiar el programa borrará las materias seleccionadas. Continuar?')) {
                        setForm({ ...form, program_id: v, subject_ids: [] });
                      }
                    } else {
                      setForm({ ...form, program_id: v, subject_ids: [] });
                    }
                  }}>
                    <SelectTrigger><SelectValue placeholder="Seleccionar programa" /></SelectTrigger>
                    <SelectContent>{programs.map(p => <SelectItem key={p.id} value={String(p.id)}>{p.name}</SelectItem>)}</SelectContent>
                  </Select>
                </div>
              </>
            )}
            {/* Subject Selection - Show for both create and edit */}
            {form.program_id && (
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <Label className="text-base">Materias del Grupo ({form.subject_ids.length} seleccionadas)</Label>
                  {filteredSubjects.length > 0 && (
                    <Button 
                      type="button" 
                      variant="ghost" 
                      size="sm" 
                      onClick={() => {
                        if (form.subject_ids.length === filteredSubjects.length) {
                          setForm({ ...form, subject_ids: [] });
                        } else {
                          setForm({ ...form, subject_ids: filteredSubjects.map(s => s.id) });
                        }
                      }}
                    >
                      {form.subject_ids.length === filteredSubjects.length ? 'Deseleccionar todas' : 'Seleccionar todas'}
                    </Button>
                  )}
                </div>
                <div className="relative">
                  <Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
                  <Input 
                    placeholder="Buscar materias..." 
                    value={subjectSearch}
                    onChange={(e) => setSubjectSearch(e.target.value)}
                    className="pl-9"
                  />
                </div>
                <div className="max-h-48 overflow-y-auto rounded-lg border p-3 space-y-2">
                  {filteredSubjects.length === 0 ? (
                    <p className="text-sm text-muted-foreground">No hay materias para este programa</p>
                  ) : (
                    filteredSubjects
                      .filter(s => (s.name || '').toLowerCase().includes(subjectSearch.toLowerCase()))
                      .map((s) => (
                        <div key={s.id} className="flex items-center gap-2">
                          <Checkbox 
                            checked={form.subject_ids.includes(s.id)} 
                            onCheckedChange={(checked) => {
                              if (checked) {
                                setForm({ ...form, subject_ids: [...form.subject_ids, s.id] });
                              } else {
                                setForm({ ...form, subject_ids: form.subject_ids.filter(id => id !== s.id) });
                              }
                            }}
                          />
                          <span className="text-sm">{s.name || 'Sin nombre'} <span className="text-muted-foreground">(Módulo {s.module_number})</span></span>
                        </div>
                      ))
                  )}
                </div>
              </div>
            )}
            {!editing && (
              <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label className="text-base">Mes</Label>
                    <Select value={form.month} onValueChange={(v) => {
                      if (v && form.year) {
                        const newName = `${v.toUpperCase()}-${form.year}`;
                        setForm({ ...form, month: v, name: newName });
                        setIsAutoGeneratedName(true);
                      } else {
                        setForm({ ...form, month: v });
                      }
                    }}>
                      <SelectTrigger><SelectValue placeholder="Seleccionar mes" /></SelectTrigger>
                      <SelectContent>
                        {['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'].map(m => (
                          <SelectItem key={m} value={m}>{m}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="space-y-2">
                    <Label className="text-base">Año</Label>
                    <Select 
                      value={form.year?.toString()} 
                      onValueChange={(value) => {
                        const newYear = parseInt(value);
                        if (form.month && newYear) {
                          const newName = `${form.month.toUpperCase()}-${newYear}`;
                          setForm({ ...form, year: newYear, name: newName });
                          setIsAutoGeneratedName(true);
                        } else {
                          setForm({ ...form, year: newYear });
                        }
                      }}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Seleccione un año" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="2024">2024</SelectItem>
                        <SelectItem value="2025">2025</SelectItem>
                        <SelectItem value="2026">2026</SelectItem>
                        <SelectItem value="2027">2027</SelectItem>
                        <SelectItem value="2028">2028</SelectItem>
                        <SelectItem value="2029">2029</SelectItem>
                        <SelectItem value="2030">2030</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
            )}
            <div className="space-y-2">
              <Label className="text-base flex items-center gap-2">
                Nombre del Grupo
                {!editing && isAutoGeneratedName && (
                  <Badge variant="secondary" className="text-xs gap-1 font-normal">
                    <Wand2 className="h-3 w-3" /> Auto-generado
                  </Badge>
                )}
              </Label>
              <Input 
                value={form.name} 
                onChange={(e) => {
                  setForm(prev => ({ ...prev, name: e.target.value }));
                  setIsAutoGeneratedName(false);
                }} 
                placeholder="Ej: ENERO-2026"
                readOnly={!editing && isAutoGeneratedName}
                className={!editing && isAutoGeneratedName ? 'bg-muted/30' : ''}
              />
              <p className="text-xs text-muted-foreground">
                {!editing
                  ? isAutoGeneratedName
                    ? 'Nombre generado automáticamente por mes y año — puedes modificarlo si lo deseas'
                    : 'Selecciona mes y año para generar el nombre automáticamente'
                  : 'Puedes editar el nombre del grupo'}
              </p>
            </div>
            {form.program_id && moduleCount > 0 && (
              <div className="space-y-3">
                <Label className="text-base">Fechas de Inicio, Cierre y Cierre de Recuperaciones por Módulo</Label>
                <div className="rounded-lg border p-4 space-y-4 bg-muted/20">
                  {Array(moduleCount).fill().map((_, i) => {
                    const moduleNum = i + 1;
                    const prevDates = form.module_dates[moduleNum - 1] || {};
                    const prevBoundary = prevDates.recovery_close || prevDates.end || '';
                    const currDates = form.module_dates[moduleNum] || {};
                    const minEnd = currDates.start || '';
                    const minRecovery = currDates.end || currDates.start || '';
                    const minStart = moduleNum > 1 ? dayAfter(prevBoundary) : '';
                    return (
                      <div key={moduleNum} className="space-y-2">
                        <p className="text-sm font-semibold text-foreground">Módulo {moduleNum}</p>
                        <div className="grid grid-cols-3 gap-3">
                          <div className="space-y-1">
                            <Label className="text-xs">Fecha Inicio</Label>
                            <Input 
                              type="date" 
                              value={form.module_dates[moduleNum]?.start || ''} 
                              min={minStart || undefined}
                              onChange={(e) => {
                                const newModuleDates = { ...form.module_dates };
                                if (!newModuleDates[moduleNum]) newModuleDates[moduleNum] = {};
                                newModuleDates[moduleNum] = { ...newModuleDates[moduleNum], start: e.target.value };
                                setForm({ ...form, module_dates: newModuleDates });
                                setModuleDateErrors(validateModuleDates(newModuleDates, moduleCount));
                              }} 
                            />
                            {moduleDateErrors[`${moduleNum}_start`] && (
                              <p className="text-xs text-destructive">{moduleDateErrors[`${moduleNum}_start`]}</p>
                            )}
                          </div>
                          <div className="space-y-1">
                            <Label className="text-xs">Fecha Cierre</Label>
                            <Input 
                              type="date" 
                              value={form.module_dates[moduleNum]?.end || ''} 
                              min={minEnd || undefined}
                              onChange={(e) => {
                                const newModuleDates = { ...form.module_dates };
                                if (!newModuleDates[moduleNum]) newModuleDates[moduleNum] = {};
                                newModuleDates[moduleNum] = { ...newModuleDates[moduleNum], end: e.target.value };
                                setForm({ ...form, module_dates: newModuleDates });
                                setModuleDateErrors(validateModuleDates(newModuleDates, moduleCount));
                              }} 
                            />
                            {moduleDateErrors[`${moduleNum}_end`] && (
                              <p className="text-xs text-destructive">{moduleDateErrors[`${moduleNum}_end`]}</p>
                            )}
                          </div>
                          <div className="space-y-1">
                            <Label className="text-xs">Cierre Recuperaciones</Label>
                            <Input 
                              type="date" 
                              value={form.module_dates[moduleNum]?.recovery_close || ''} 
                              min={minRecovery || undefined}
                              onChange={(e) => {
                                const newModuleDates = { ...form.module_dates };
                                if (!newModuleDates[moduleNum]) newModuleDates[moduleNum] = {};
                                newModuleDates[moduleNum] = { ...newModuleDates[moduleNum], recovery_close: e.target.value };
                                setForm({ ...form, module_dates: newModuleDates });
                                setModuleDateErrors(validateModuleDates(newModuleDates, moduleCount));
                              }} 
                            />
                            {moduleDateErrors[`${moduleNum}_recovery_close`] && (
                              <p className="text-xs text-destructive">{moduleDateErrors[`${moduleNum}_recovery_close`]}</p>
                            )}
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </div>
                <p className="text-xs text-muted-foreground">
                  Define el período de cada módulo y la fecha límite para recuperaciones
                </p>
              </div>
            )}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <Label className="text-base">Estudiantes Inscritos ({form.student_ids.length} seleccionados)</Label>
                {(() => {
                  if (!editing && !form.program_id) return null;
                  // Students removed from THIS course due to failed recovery cannot re-join it
                  const removedFromThisCourse = editing ? (editing.removed_student_ids || []) : [];
                  const eligible = students.filter(s => {
                    // Always include students already enrolled in the current group
                    if (editing && form.student_ids.includes(s.id)) return true;
                    // Exclude students previously removed from this course due to failed recovery
                    if (removedFromThisCourse.includes(s.id)) return false;
                    // Only active students are eligible to enroll (check per-program status when available)
                    if (getStudentStatusForProgram(s, form.program_id) !== 'activo') return false;
                    if (!form.program_id) return true;
                    const programIds = s.program_ids || (s.program_id ? [s.program_id] : []);
                    if (programIds.length > 0 && !programIds.map(String).includes(String(form.program_id))) return false;
                    // Filter by module: student's current module for this program must match the group module
                    if (groupModule != null) {
                      const studentMod = parseInt((s.program_modules || {})[form.program_id] ?? s.module, 10);
                      if (Number.isFinite(studentMod) && studentMod !== groupModule) return false;
                    }
                    // Exclude students already enrolled in another group of the same program
                    const currentEditingId = editing?.id;
                    const inOtherGroup = courses.some(c =>
                      c.id !== currentEditingId &&
                      String(c.program_id) === String(form.program_id) &&
                      (c.student_ids || []).includes(s.id)
                    );
                    if (inOtherGroup) return false;
                    return true;
                  });
                  return eligible.length > 0 && (
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      onClick={() => {
                        if (form.student_ids.length === eligible.length) {
                          setForm({ ...form, student_ids: [] });
                        } else {
                          setForm({ ...form, student_ids: eligible.map(s => s.id) });
                        }
                      }}
                    >
                      {form.student_ids.length === eligible.length ? 'Deseleccionar todos' : 'Seleccionar todos'}
                    </Button>
                  );
                })()}
              </div>
              <div className="relative">
                <Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
                <Input 
                  placeholder="Buscar estudiantes por nombre o cédula..." 
                  value={studentSearch}
                  onChange={(e) => setStudentSearch(e.target.value)}
                  className="pl-9"
                />
              </div>
              <div className="max-h-48 overflow-y-auto rounded-lg border p-4 space-y-2.5">
                {(() => {
                  // When creating (not editing) and no program selected, show a prompt instead of all students
                  if (!editing && !form.program_id) {
                    return <p className="text-sm text-muted-foreground">Selecciona un técnico primero para ver estudiantes elegibles</p>;
                  }
                  // Students removed from THIS course due to failed recovery cannot re-join it
                  const removedFromThisCourse = editing ? (editing.removed_student_ids || []) : [];
                  const eligible = students.filter(s => {
                    const matchesSearch = (s.name || '').toLowerCase().includes(studentSearch.toLowerCase()) ||
                      (s.cedula && s.cedula.includes(studentSearch));
                    if (!matchesSearch) return false;
                    // Always include students already enrolled in the current group
                    if (editing && form.student_ids.includes(s.id)) return true;
                    // Exclude students previously removed from this course due to failed recovery
                    if (removedFromThisCourse.includes(s.id)) return false;
                    // Only active students are eligible to enroll (check per-program status when available)
                    if (getStudentStatusForProgram(s, form.program_id) !== 'activo') return false;
                    // Filter by program: show only students enrolled in this course's program
                    if (form.program_id) {
                      const programIds = s.program_ids || (s.program_id ? [s.program_id] : []);
                      if (programIds.length > 0 && !programIds.map(String).includes(String(form.program_id))) return false;
                    }
                    // Filter by module: student's current module for this program must match group module
                    if (groupModule != null && form.program_id) {
                      const studentMod = parseInt((s.program_modules || {})[form.program_id] ?? s.module, 10);
                      if (Number.isFinite(studentMod) && studentMod !== groupModule) return false;
                    }
                    // Exclude students already enrolled in another group of the same program
                    if (form.program_id) {
                      const currentEditingId = editing?.id;
                      const inOtherGroup = courses.some(c =>
                        c.id !== currentEditingId &&
                        String(c.program_id) === String(form.program_id) &&
                        (c.student_ids || []).includes(s.id)
                      );
                      if (inOtherGroup) return false;
                    }
                    return true;
                  });
                  if (students.length === 0) return <p className="text-sm text-muted-foreground">No hay estudiantes</p>;
                  if (eligible.length === 0) return <p className="text-sm text-muted-foreground">No hay estudiantes elegibles (activos, compatibles con el programa{groupModule != null ? ` y Módulo ${groupModule}` : ''} seleccionado)</p>;
                  return eligible.map((s) => (
                    <div key={s.id} className="flex items-center gap-2.5">
                      <Checkbox checked={form.student_ids.includes(s.id)} onCheckedChange={() => toggleStudent(s.id)} />
                      <span className="text-sm">{s.name || 'Sin nombre'} <span className="text-muted-foreground">({s.cedula}) - Módulo {s.module} - {getStudentStatusForProgram(s, form.program_id) === 'activo' ? 'Activo' : 'Egresado'}</span></span>
                    </div>
                  ));
                })()}
              </div>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDialogOpen(false)}>Cancelar</Button>
            <Button onClick={handleSave} disabled={saving}>{saving && <Loader2 className="h-4 w-4 animate-spin" />}{editing ? 'Actualizar' : 'Crear'}</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </DashboardLayout>
  );
}
